import Verso
import VersoManual
import VersoBlueprint
import Blueprint.Commands

import MultilinearInterpolation

open Verso.Genre Manual Informal

set_option verso.blueprint.foldCodeBlocks true

#doc (Manual) "Extended quasinorms" =>
%%%
htmlSplit := .never
%%%

Compatible couples of spaces equipped with a quasinorm are defined as subspaces of some ambient
space $`α`. For this reason, we represent each subspace with a quasinorm as an extended quasinorm in
the whole space $`α`. Points that are outside of the subspace have their extended norm assigned
to be $`+∞`.

In the previous paragraph, we have not specified what notion of "space" we are
dealing with, and we have not specified a topology on the ambient space. For
the project, the spaces will be at least additive monoids but extra structure will
be required in more specific parts of the proof. A Hausdorff topology on the
ambient space that coincides with the topology generated by the quasinorm of
both subspaces is only necessary if we want to conclude definitiness of the norm on
the sum of the couple (and therefore for its interpolation spaces). Similarly,
completeness is only necessary if we want to conclude completeness for the
interpolation spaces.

We don't make statements using those extra assumptions as they are not necessary for
stating the boundedness of the operator in the interpolation space. Moreover,
if we prove that the norm of the interpolation space is equivalent to the norm
in some well-known space which has a complete norm, then the operator will be
bounded for that space and the completeness of the norm is already known. Showing that the
interpolation spaces satisfy more properties depending on the properties of the
starting couple may also be done as a separate step later.

{blueprint_nodes_in EQuasinorm}
